# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('ID_Factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField()),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellido', models.CharField(max_length=25)),
                ('Cedula', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Producto', models.CharField(max_length=10)),
                ('Cantidad_por_pesada', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio_actual', models.DecimalField(decimal_places=10, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='login_administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_usuario_adm', models.CharField(max_length=25)),
                ('ID_clave_adm', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login_facturador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_usuario_facturador', models.CharField(max_length=25)),
                ('ID_clave_facturador', models.CharField(max_length=25)),
                ('Nombre_del_facturador', models.CharField(max_length=25)),
                ('Apellido_del_facturador', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_precio', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
