# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Cantidad_por_pesada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='precio_actual',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_pagar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='precio',
            name='ID_precio',
            field=models.FloatField(),
        ),
    ]
